services:
  mysql:
    image: mysql:8.0
    container_name: has-mysql-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-qwer1234}
      MYSQL_DATABASE: ${DATABASE_NAME:-has}
      MYSQL_USER: ${DATABASE_USERNAME:-mysql}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-qwer1234}
      TZ: ${TZ:-Asia/Seoul}
    volumes:
      - ./data/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: has-redis-local
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis1234} --appendonly yes --bind 0.0.0.0
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis1234}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5